[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["express", "cors", "dotenv", "mongoose", "openai", "serverless-http", "zod"]
  node_bundler = "esbuild"
